import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { GoogleOAuthProvider } from "@react-oauth/google";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={outfit.className}
      data-theme="light"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
          <ReduxProvider>
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </ReduxProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}




// import "slick-carousel/slick/slick.css"; 
// import "slick-carousel/slick/slick-theme.css";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Outfit } from "next/font/google";
// import "./globals.css";
// import ReduxProvider from "@/redux/provider";
// import "react-toastify/dist/ReactToastify.css";
// import { ToastContainer } from "react-toastify";
// // import { GoogleOAuthProvider } from '@react-oauth/google';
// import { GoogleOAuthProvider } from "@react-oauth/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const outfit = Outfit({
//   variable: "--font-outfit",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       suppressHydrationWarning
//       className={outfit.className}
//       data-theme="light"
//     >
//     <html lang="en" suppressHydrationWarning className={outfit.className} data-theme="light">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <GoogleOAuthProvider
//           clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
//         >
//           <ReduxProvider>
//             {children}
//             <ToastContainer position="top-right" autoClose={3000} />
//           </ReduxProvider>
//         </GoogleOAuthProvider>
//         <ReduxProvider>
//           {children}
//           <ToastContainer position="top-right" autoClose={3000} />
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }
